name: work_hub_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  fluttericon: ^2.0.0
  url_launcher: ^6.1.14
  curved_navigation_bar: ^1.0.3
  uuid: ^4.1.0
  fluttertoast: ^8.2.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf


